spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 120
      minimum-idle: 100
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      keepalive-time: 240000
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.example.oracletest: INFO
    com.zaxxer.hikari: INFO